---
title: "Complexity"
author: "phebden"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(ggtext)
```

### Algorithms: Big O 
[ https://en.wikipedia.org/wiki/Big_O_notation ]
```{r  warning=FALSE, message=FALSE, out.width="60%"}
n=1:20
y1 = n * log(n)
y2 = choose(n,3)
y3 = 2^n
df = tibble(y1=y1, y2=y2, y3=y3)

ggplot(df, aes(x=n)) +
  ylim(0,1200) +
  geom_line(aes(y=y1, colour = "y1"))  + 
  geom_line(aes(y=y2, colour = "y2")) +
  geom_line(aes(y=y3, colour = "y3"))   +
  scale_colour_manual("", values = c("y1"="blue", "y2"="green", "y3"="red"),
    labels=c("n log n", "n choose m", expression(paste(2^n))), name="Big O") +
  labs(x = "n", y = "time") +
  theme_minimal() + theme(plot.title = element_text(size = 15)) +
  ggtitle("Complexity depends on n, m=3") 
  
mainDir="."; subDir="figures"
dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
#ggsave(filename = "./figures/Big-O.pdf")
```


